FOS\UserBundle\Model\User:
  properties:
    username:
      - NotBlank:
          message: "Der Nutzername darf nicht leer sein"
      - Length:
          minMessage: "Dein Nutzername ist zu kurz"
          maxMessage: "Dein Nutzername ist zu lang"
      email:
      - NotBlank:
          message: "Die E-Mail darf nicht leer sein"
      - Length:
          minMessage: "Deine E-Mail ist zu kurz"
          maxMessage: "Deine E-Mail ist zu lang"
      - Email:
          message: "Deine angebene E-Mail ist flash"
    plainPassword:
      - NotBlank:
          message: "Dein Passwort darf nicht leer sein"
      - Length:
          minMessage: "Dein Passwort ist zu kurz"